### ISSUE TITLE
并未生成start.lua

### ISSUE THREAD

**Issue by rve** [binux/ankulua-vision#1]
mac端，meta.json, screens和images正常生成，其他就没了。

另，release里的ankulua-vision-mas-x64 拼成了mas。

**Comment by binux** [comment]
那你去 https://github.com/binux/ankulua-vision/tree/master/static 下面把3个 .lua 拷贝过去就行了。
mas 是这个 vue-electron 模板就这么叫的，我也不知道为什么。

**Comment by rve** [comment]
Thanks
