### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by nevrending** [binux/ankulua-vision#2]
Hi. I'm experiencing this error when running `npm install`.

OS: Mac OSX 10.12.6
npm: 6.70
node: v11.13.0
Python: 3.7.3
I'm using Homebrew's python.

![image](https://user-images.githubusercontent.com/4745298/55310513-50e7fe00-54ac-11e9-987b-54d12b00c9d7.png)

**Comment by binux** [comment]
try install python2
It's a dependency error of canvas, try get help from them.

**Comment by nevrending** [comment]
Alright, thank you!
`brew install python@2` fixed that.

In case anyone else experiencing the same problem, I also encountered `Package cairo was not found in the pkg-config search path.` which I found this solution worked: https://stackoverflow.com/a/27705973
